#!/usr/bin/env bash
# Installs and configures HAProxy on the lb-01 server

# Update package list and install HAProxy
apt-get update
apt-get -y install haproxy

# Configure HAProxy with round-robin algorithm
cat <<EOF >> /etc/haproxy/haproxy.cfg

frontend my_frontend
    bind *:80
    mode http
    default_backend my_servers

backend my_servers
    mode http
    balance roundrobin
    server 7032-web-01 13.221.234.18:80 check
    server 7032-web-02 3.83.134.172:80 check
EOF

# Restart HAProxy to apply the configuration
service haproxy restart
