#!/usr/bin/env bash
# Installs and configures HAProxy on a new Ubuntu server to load-balance two web servers

WEB1_IP="13.221.234.18"
WEB2_IP="3.83.134.172"
#install HAProxy
apt-get update -y
apt-get install -y haproxy

# Enable HAProxy to start on boot
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

#load balancing configuration
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 $WEB1_IP:80 check
    server web-02 $WEB2_IP:80 check
EOF

# Restart HAProxy to apply configuration
service haproxy restart
