#!/usr/bin/env bash
# Installs and configures Nginx on a new Ubuntu machine

apt-get update -y
apt-get install -y nginx

# Set the default index page to return "Holberton School"
# In your 1-install_nginx_web_server script
echo "Holberton School" | sudo tee /var/www/html/index.html

# Ensure Nginx is running
service nginx start
