#!/usr/bin/env bash
# This script installs and configures Nginx

apt-get update -y
apt-get install nginx -y

echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

service nginx start