#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me

apt-get update -y
apt-get install nginx -y

echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

sed -i '/server_name _;/a \ \ \ \ location /redirect_me {\n \ \ \ \ \ \ return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n \ \ \ \ }' /etc/nginx/sites-available/default

service nginx restart