#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to a new URL

apt-get update -y
apt-get install -y nginx

# Configure the 301 redirect using sed
# This inserts the rewrite rule inside the server block
REDIRECTION="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sed -i "/server_name _;/a $REDIRECTION" /etc/nginx/sites-available/default

service nginx restart
