#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me with a 301 status code

# Update and install Nginx
apt-get update -y
apt-get install nginx -y

redirect_config="location = /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGU1wu4;
}"

sed -i "/server_name _;/a \\
    $redirect_config" /etc/nginx/sites-available/default

# Test configuration and restart
nginx -t && service nginx restart