#!/usr/bin/env bash
# Configures a custom 404 page

# Update and install Nginx
apt-get update -y
apt-get install -y nginx

# Create the custom 404 page content with the mandatory string
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
ERROR_PAGE_CONF="error_page 404 /custom_404.html;"
LOCATION_CONF="location = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"

sed -i "/server_name _;/a \    $ERROR_PAGE_CONF" /etc/nginx/sites-available/default
sed -i "/error_page 404 \/custom_404.html;/a \    $LOCATION_CONF" /etc/nginx/sites-available/default

# Restart service without using systemctl
service nginx restart