#!/usr/bin/env bash
# Configure Nginx with a custom 404 page

apt-get update -y
apt-get install nginx -y

# Default page
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.nginx-debian.html;

    server_name _;

    error_page 404 /404.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart Nginx
service nginx restart