#!/usr/bin/env bash
# Configures a custom 404 page

apt-get update -y
apt-get install -y nginx

# Create the custom 404 page content
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
# Use sed to add the error_page and location blocks
ERROR_CONF="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sed -i "/server_name _;/a $ERROR_CONF" /etc/nginx/sites-available/default

service nginx restart
